from __future__ import annotations

from pathlib import Path

from .base import AsrProvider, AsrProviderError, AsrTranscript, ProviderStatus
from .config import LocalSpeechConfig
from .sherpa_provider import SherpaOnnxAsrProvider
from .vosk_provider import VoskAsrProvider


class AsrRegistry:
    def __init__(self, config: LocalSpeechConfig) -> None:
        self.config = config
        self._providers: dict[str, AsrProvider] = {
            "vosk": VoskAsrProvider(
                model_path=config.vosk_model_path,
                project_root=config.project_root,
                enabled=config.enable_vosk,
            ),
            "sherpa": SherpaOnnxAsrProvider(
                model_dir=config.sherpa_model_dir,
                project_root=config.project_root,
                enabled=config.enable_sherpa,
            ),
        }
        self.latest_segment_path: Path | None = None

    @property
    def default_provider_name(self) -> str:
        return self.config.default_provider or "vosk"

    @property
    def auto_transcribe_enabled(self) -> bool:
        return self.config.auto_transcribe and bool(self.config.default_provider)

    def list_statuses(self) -> list[ProviderStatus]:
        return [provider.status() for provider in self._providers.values()]

    def get_provider(self, provider_name: str | None = None) -> AsrProvider:
        normalized = (provider_name or self.default_provider_name).strip().lower()
        provider = self._providers.get(normalized)
        if provider is None:
            raise AsrProviderError(
                provider=normalized or "unknown",
                code="unknown_provider",
                message=f"Unknown ASR provider: {normalized}",
                setup_hint="Use one of: vosk, sherpa.",
                details={"available_provider_names": list(self._providers)},
            )
        return provider

    def provider_status(self, provider_name: str | None = None) -> ProviderStatus:
        return self.get_provider(provider_name).status()

    def load_provider(self, provider_name: str | None = None) -> ProviderStatus:
        return self.get_provider(provider_name).load()

    def remember_segment(self, path: Path) -> None:
        self.latest_segment_path = path.resolve()

    def resolve_recording_path(self, filename_or_path: str | None) -> Path:
        if not filename_or_path:
            raise AsrProviderError(
                provider="registry",
                code="segment_path_missing",
                message="No WAV segment filename or path was provided.",
                setup_hint="Create a VAD segment first or pass a segment filename.",
            )

        candidate = Path(filename_or_path)
        if not candidate.is_absolute():
            candidate = self.config.recordings_dir / candidate

        resolved = candidate.resolve()
        recordings_dir = self.config.recordings_dir.resolve()
        if not resolved.is_relative_to(recordings_dir):
            raise AsrProviderError(
                provider="registry",
                code="segment_path_outside_recordings",
                message="ASR can only transcribe WAV files from local_speech_engine/recordings.",
                setup_hint="Pass a saved segment filename from the Local VAD panel.",
                details={"path": str(resolved), "recordings_dir": str(recordings_dir)},
            )

        if not resolved.exists() or not resolved.is_file():
            raise AsrProviderError(
                provider="registry",
                code="segment_not_found",
                message=f"WAV segment was not found: {resolved.name}",
                setup_hint="Create a VAD recording first, then transcribe the saved segment.",
                details={"path": str(resolved)},
            )

        if resolved.suffix.lower() != ".wav":
            raise AsrProviderError(
                provider="registry",
                code="segment_not_wav",
                message="ASR only accepts saved .wav segments.",
                setup_hint="Use a WAV file generated by the local VAD sidecar.",
                details={"path": str(resolved)},
            )

        return resolved

    def latest_recording_path(self) -> Path:
        if self.latest_segment_path is None:
            raise AsrProviderError(
                provider="registry",
                code="latest_segment_missing",
                message="No latest VAD segment is available yet.",
                setup_hint="Start VAD, say a short word, wait for segment_saved, then transcribe latest.",
            )

        return self.resolve_recording_path(str(self.latest_segment_path))

    def transcribe_segment(self, provider_name: str | None, filename_or_path: str | None) -> AsrTranscript:
        path = self.resolve_recording_path(filename_or_path)
        provider = self.get_provider(provider_name)
        return provider.transcribe_wav(path)

    def transcribe_latest(self, provider_name: str | None = None) -> AsrTranscript:
        path = self.latest_recording_path()
        provider = self.get_provider(provider_name)
        return provider.transcribe_wav(path)

