from __future__ import annotations

import json
import shutil
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ENGINE_ROOT = Path(__file__).resolve().parent
DEFAULT_RECORDINGS_DIR = ENGINE_ROOT / "recordings"
DEFAULT_CORPUS_DIR = ENGINE_ROOT / "audio_corpus"
DEFAULT_LABELS_PATH = DEFAULT_CORPUS_DIR / "labels.json"

VALID_SAMPLE_TYPES = {"command", "voice_note"}
COMMAND_CATEGORIES = {"colors", "shapes", "numbers", "other"}


@dataclass
class CorpusError(Exception):
    code: str
    message: str
    setup_hint: str = ""
    details: dict[str, Any] = field(default_factory=dict)

    def __str__(self) -> str:
        return self.message

    def to_event_payload(self) -> dict[str, Any]:
        return {
            "code": self.code,
            "message": self.message,
            "setup_hint": self.setup_hint,
            "details": self.details,
        }


def utc_timestamp() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def load_labels(labels_path: Path | None = None) -> list[dict[str, Any]]:
    path = labels_path or DEFAULT_LABELS_PATH
    if not path.exists():
        return []

    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise CorpusError(
            code="labels_json_invalid",
            message=f"Corpus labels file is not valid JSON: {path}",
            setup_hint="Fix labels.json or move it aside and save a new labeled sample.",
            details={"path": str(path), "error": str(error)},
        ) from error

    if isinstance(payload, list):
        return [item for item in payload if isinstance(item, dict)]

    if isinstance(payload, dict) and isinstance(payload.get("samples"), list):
        return [item for item in payload["samples"] if isinstance(item, dict)]

    raise CorpusError(
        code="labels_json_shape_invalid",
        message="Corpus labels must be a JSON array or an object with a samples array.",
        setup_hint="Use local_speech_engine/audio_corpus/labels.json for labeled WAV metadata.",
        details={"path": str(path)},
    )


def write_labels(labels: list[dict[str, Any]], labels_path: Path | None = None) -> None:
    path = labels_path or DEFAULT_LABELS_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(labels, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")


def resolve_recording_wav(source_filename: str | None, recordings_dir: Path = DEFAULT_RECORDINGS_DIR) -> Path:
    if not source_filename or not str(source_filename).strip():
        raise CorpusError(
            code="source_missing",
            message="No source WAV filename was provided.",
            setup_hint="Create a VAD segment first, then save the latest segment to the corpus.",
        )

    candidate = Path(str(source_filename).strip())
    if not candidate.is_absolute():
        candidate = recordings_dir / candidate

    resolved = candidate.resolve()
    recordings_root = recordings_dir.resolve()
    if not resolved.is_relative_to(recordings_root):
        raise CorpusError(
            code="source_outside_recordings",
            message="Corpus samples can only be copied from local_speech_engine/recordings.",
            setup_hint="Pass a saved VAD segment filename from the Local VAD panel.",
            details={"path": str(resolved), "recordings_dir": str(recordings_root)},
        )

    if not resolved.exists() or not resolved.is_file():
        raise CorpusError(
            code="source_not_found",
            message=f"Source WAV segment was not found: {resolved.name}",
            setup_hint="Create a VAD recording first, then save the saved segment as a labeled sample.",
            details={"path": str(resolved)},
        )

    if resolved.suffix.lower() != ".wav":
        raise CorpusError(
            code="source_not_wav",
            message="Only .wav VAD segments can be saved to the ASR corpus.",
            setup_hint="Use a WAV file generated by the local VAD sidecar.",
            details={"path": str(resolved)},
        )

    return resolved


def normalize_sample_type(value: str | None) -> str:
    sample_type = str(value or "command").strip().lower()
    if sample_type not in VALID_SAMPLE_TYPES:
        raise CorpusError(
            code="sample_type_invalid",
            message=f"Unsupported corpus sample type: {sample_type}",
            setup_hint="Use type 'command' or 'voice_note'.",
            details={"sample_type": sample_type},
        )
    return sample_type


def normalize_category(sample_type: str, value: str | None) -> str:
    category = str(value or ("other" if sample_type == "command" else "trial_note")).strip().lower()
    category = category.replace(" ", "_")
    if sample_type == "command" and category not in COMMAND_CATEGORIES:
        return "other"
    if not category:
        return "other" if sample_type == "command" else "trial_note"
    return category


def sample_folder(sample_type: str, category: str) -> Path:
    if sample_type == "command":
        return Path("commands") / category
    return Path("voice_notes")


def save_segment_to_corpus(
    *,
    source_filename: str | None,
    expected: str | None,
    sample_type: str | None = "command",
    category: str | None = "other",
    notes: str | None = "",
    recordings_dir: Path = DEFAULT_RECORDINGS_DIR,
    corpus_dir: Path = DEFAULT_CORPUS_DIR,
    labels_path: Path | None = None,
) -> dict[str, Any]:
    expected_text = str(expected or "").strip()
    if not expected_text:
        raise CorpusError(
            code="expected_missing",
            message="Expected transcript text is required for a corpus sample.",
            setup_hint="Enter the word or phrase the WAV should contain.",
        )

    source_path = resolve_recording_wav(source_filename, recordings_dir)
    normalized_type = normalize_sample_type(sample_type)
    normalized_category = normalize_category(normalized_type, category)
    destination_dir = corpus_dir / sample_folder(normalized_type, normalized_category)
    destination_dir.mkdir(parents=True, exist_ok=True)
    destination_path = destination_dir / source_path.name
    shutil.copy2(source_path, destination_path)

    resolved_labels_path = labels_path or corpus_dir / "labels.json"
    labels = load_labels(resolved_labels_path)
    relative_file = destination_path.relative_to(corpus_dir).as_posix()
    existing = next((label for label in labels if label.get("file") == relative_file), None)

    if existing:
        existing.update(
            {
                "file": relative_file,
                "expected": expected_text,
                "type": normalized_type,
                "category": normalized_category,
                "notes": str(notes or "").strip(),
            }
        )
        sample = existing
    else:
        sample = {
            "id": f"sample_{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%S%fZ')}_{uuid.uuid4().hex[:8]}",
            "file": relative_file,
            "expected": expected_text,
            "type": normalized_type,
            "category": normalized_category,
            "notes": str(notes or "").strip(),
            "created_at": utc_timestamp(),
        }
        labels.append(sample)

    seen_ids: set[str] = set()
    for label in labels:
        label_id = str(label.get("id") or "")
        if not label_id or label_id in seen_ids:
            label["id"] = f"sample_{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%S%fZ')}_{uuid.uuid4().hex[:8]}"
        seen_ids.add(str(label["id"]))

    labels.sort(key=lambda label: str(label.get("created_at") or ""))
    write_labels(labels, resolved_labels_path)
    return dict(sample)
